// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dailyamount-history/Current.tsx": () => import("../components/mockups/dailyamount-history/Current.tsx"),
  "./components/mockups/dailyamount-history/ReferenceRedesign.tsx": () => import("../components/mockups/dailyamount-history/ReferenceRedesign.tsx"),
  "./components/mockups/dailyamount-login/Current.tsx": () => import("../components/mockups/dailyamount-login/Current.tsx"),
  "./components/mockups/dailyamount-login/LoginReference.tsx": () => import("../components/mockups/dailyamount-login/LoginReference.tsx"),
  "./components/mockups/dailyamount/Current.tsx": () => import("../components/mockups/dailyamount/Current.tsx"),
  "./components/mockups/dailyamount/ReferenceRedesign.tsx": () => import("../components/mockups/dailyamount/ReferenceRedesign.tsx")
};
